export const GET_PLAYERLIST_REQUEST = "GET_PLAYERLIST_REQUEST";
export const GET_PLAYERLIST_SUCCESS = "GET_PLAYERLIST_SUCCESS";
export const GET_PLAYERLIST_FAIL = "GET_PLAYERLIST_FAIL";

export const GET_PLAYERDETAILS_REQUEST = "GET_PLAYERDETAILS_REQUEST";
export const GET_PLAYERDETAILS_SUCCESS = "GET_PLAYERDETAILS_SUCCESS";
export const GET_PLAYERDETAILS_FAIL = "GET_PLAYERDETAILS_FAIL";